### ISSUE TITLE
Glossary links don't scroll enough.

### ISSUE THREAD

**Issue by MicahZoltu** [msagansk/Augur.Guide#7]
If you click a glossary link, it scrolls such that the vertical center of the glossary entry is at the top of the page, meaning the top of the entry is cut off.  Example: https://augur.guide/glossary.html#Participation%20Token

One easy solution to this I think would be to make the glossary "Term" column be aligned to the top of the table rather than the vertical center of the table.  This way the anchor should take you to the top of the glossary entry instead of the middle.

**Comment by msagansk** [comment]
Fixed, as suggested. I also changed some of the spacing so that long terms don't cause a line break (at least, on a desktop). The anchor was going inbetween the words of the term, wherever they happen to be.
